### ISSUE TITLE
Add package,json provide section

### ISSUE THREAD

**Issue by majerm** [contributte/psr11-container-interface#5]
You can add provide section to composer.json (like here https://github.com/symfony/dependency-injection/blob/master/composer.json) to show package in this listing https://packagist.org/providers/psr/container-implementation

**Comment by mabar** [comment]
Interesting, thanks.

@f3l1x We could probably add it to all PSR-implementing packages?

**Comment by f3l1x** [comment]
Sure. Let's do it.

**Comment by mabar** [comment]
Closed by https://github.com/contributte/psr11-container-interface/commit/4bed4fc4fce26a2911905438303945237df0c81a
